### ISSUE TITLE
holy

### ISSUE THREAD

**Issue by fuji321** [octocat/Hello-World#160]
sssit

**Comment by sharstream** [comment]
Hi

**Comment by qwer99x** [comment]
hi hello **V

**Comment by saharAP** [comment]
hello

---

*two things are infinite the universe and human stupiditybut I'm not sure
about the universeEinsteinz.apanahloo@aut.ac.ir

## z.apanahloo@aut.ac.irsahar.aplo@gmail.com sahar.aplo@gmail.com*

**Comment by ghost** [comment]
Hello you'll. ¿any comments?

**Comment by gsanch15** [comment]
howdy

**Comment by Crankyt** [comment]
Heyyy

**Comment by sharstream** [comment]
Hi who is you i am c++ software developer where are you from

**Comment by DavidZeng0202** [comment]
I think what you want to ask is "who are you" not "who is you".

**Comment by ghost** [comment]
Hey there!
m new here..want to learn how to write small games in C :)
Ill be thankfull

**Comment by JiangSuyong** [comment]
I think there are a lot of you is not use english as mother language.yes so am i,I from china,I am very happy to make friends all over the world! : )

**Comment by yelangya3826850** [comment]
I have received a e-mail which says "I think what you want to ask is "who are you" not "who is you".", I was freak out and came to have a look.

**Comment by gitspart** [comment]
what's up ?  why have so many emails appeared in my mail box ?

hello ,guys!

------------------ 原始邮件 ------------------
发件人: "MengNan";notifications@github.com;
发送时间: 2014年7月25日(星期五) 中午1:10
收件人: "octocat/Hello-World"Hello-World@noreply.github.com; 

主题: Re: [Hello-World] holy (#160)

I have received a e-mail which says "I think what you want to ask is "who are you" not "who is you".", I was freak out and came to have a look.

**Comment by saharAP** [comment]
hello guys
 I'm new in github .
I'm java developer and i love java ,but I want to learn python because its
so fast and simple

---

*two things are infinite the universe and human stupiditybut I'm not sure
about the universeEinsteinz.apanahloo@aut.ac.ir

## z.apanahloo@aut.ac.irsahar.aplo@gmail.com sahar.aplo@gmail.com*

**Comment by ghost** [comment]
HI friends, why can't we discuss something about developing a new software or any application, since we are from different places with different kinds of technological knowledge. I know Java, Html, Css, Javascript, Jquery. Let us introduce our self once and lets start discussing something wonderful which we can make all together. It would be interesting. Please...lets share our ideas..

Thank you, 
Shravan from India.

**Comment by sharstream** [comment]
Hi let us do something I am c++ software developer

**Comment by ciurtin** [comment]
ok a lot of hi around here....the thing is that we should start with something(even if is something very small...but we have a start)...and now to move to serious things...how many of u get to this page cause of VirtaCoin?...we need to have a starting point so we know what the fuck we want...waiting for reply...a good day to all

**Comment by ghost** [comment]
Hi Ciurtin,
Yes you are right, we need a starting point. we can start with a small, later it can be developed into big. By the way what is that you mentioned "VirtaCoin". Can you point me out with additional details?

And people, just jot down our names with our expertise in the technology so that we can be sure that we have sufficient tech resources at our disposal.

Thank you,
Shravan, India

**Comment by ciurtin** [comment]
hi 
I got on this site cause of VirtaCoin....if u never heard about it try to search on Google...Bitcoin(or even better on Wikipedia)...so you gone have a idea about what i am talking about...because is the same principle...but also if u talking about starting with small apps that will do also...but i think is not so much about writing the code...is more about talking about ideas and coming up with clever ways to implement them...but for this all of us need to jump in...because I don't care so much  about your experience...is more about if u think about an idea...let's see if we can work with it...my opinion(by the way..i am good with C and C++...and a little bit of web design)

**Comment by piter50** [comment]
I'm all for developers getting together and starting a project and
collaborating, but do you think you can start a Google group or something
and post it rather than use the hello world notification list?

Much appreciated

**Comment by ghost** [comment]
Hi Piter,

It is really a good idea, before starting our journey, lets decide a perfect place to talk or discuss. We need to settle first like in a group. A good place where we can discuss without any confusion.

Any suggestion from you guys, which group would be good? Even skype is also good for group chatting. Ok, lets create a group in google first, please decide a name, I will be creating a google group on that name and then we will start adding members who are all really interested in the project.

My email ID is tshravan2012@gmail.com and my skype id is "shravanz".

Thank you guys, and you all knew this, slow and steady wins the race.. :) lets take this slowly with careful attention.

Shravan, India.

**Comment by qwer99x** [comment]
http://bit.ly/U531QC 

只漲不跌的理財方法！！
如果你想理財、存錢、賺錢、不想花大錢、不想拉人、不重銷、不想屯貨、不想上激勵的成功學課程、不想一直在網路上PO文賣產品，我想這個平台真的是很適合你來瞭解看看!！
http://t.cn/RPvb9Hd

**Comment by ghost** [comment]
hi guys,
anybody interested?? I need to know who are all interested in doing a collaborated project. I have given myself a time of 2 weeks. Within 2 weeks people are welcome to join, just say hi here as well as your experience in technical field and what technologies you are well versed with.

Thank you so much,

Shravan, India

**Comment by accribus** [comment]
I am comfortable with java and JavaScript.

**Comment by ubir1** [comment]
Hi,
I am Abir from Bangladesh, I am interested in Software Testing Projects like Unit testing or developing automation framework, automation testing with various librarious or developing new testing libraries, or secuirity or load testing scripts or anything, if anyone likes this, please knock.

**Comment by ghost** [comment]
Hey.

This is Mairaj. And I am learning to code.

Regards

**Comment by ajpen** [comment]
Im comfortable with C. Looking to be comfortable with others.

**Comment by ghost** [comment]
Hi!

**Comment by BetterBestBai** [comment]
Hi，
I have learned C/C++,VB,and python,but I have not do one project, what can I help you.

**Comment by lapinflying** [comment]
Hi,

I have some basic experience on C++ and Python, I'm eager to learn more
things from u. Nice to hear u.

Chen

2014-08-07 10:56 GMT+02:00 baizhendie notifications@github.com:

**Comment by ghost** [comment]
Yo, guys.
I know C++ and Python basics. That'd be just cool if I could use my knowledge somehow in a real project.

**Comment by qwer99x** [comment]
免專業、免開口、免花錢
開放手機免費下載加入，介紹人請填ID : v v 5 8 5 8
開放手機免費下載加入，介紹人請填ID : v v 5 1 6 8

ICUE 手機下載網址:   http://icue.im

不想靠ICUE賺錢的人也可以免費使用ICUE來當和客戶朋友溝通的工具
我們如果可以接受韓國的line,應該也可以接受英國的ICUE吧

讓大家都可免費加入,又可免費找人賺錢的事業,而且全球皆可推廣找人才
9月開始廣告收入最高9000/月+紅利+免費推廣200禮卷可拿

Ps: 請到後台登入您的 ID..確認加入及帶您入社團群組

http://0rz.tw/ii87T

**Comment by qwer99x** [comment]
Free professional, free opening, free money 
Open Mobile free download join Referrals please fill ID: vv 5 8 5 8 
Open Mobile free download join Referrals please fill ID: vv 5 1 6 8 

ICUE Mobile Download URL: http://icue.im 

Do not want people to make money by ICUE free use ICUE to friends and clients as a tool to communicate 
If we can accept Korea's line, should be able to accept British ICUE it 

So that everyone can be free to join, free to find someone to make money but also the cause of, and to promote global Jieke looking for talent 
Beginning September highest advertising revenue 9000 / month + bonus + free promotion 200 voucher to be had 

Ps: Go back to your login ID .. sure to join the group and take you into the community 

http://0rz.tw/ii87T

**Comment by BetterBestBai** [comment]
Hi,
In fact I also have the basic knowledge so I want to do some project to get improvements, I think we can help each other, so we can improve ourselves together
Glad to hear u
yours sincerely
 Bai

------------------ 原始邮件 ------------------
发件人: "lapinflying";notifications@github.com;
发送时间: 2014年8月7日(星期四) 晚上8:55
收件人: "octocat/Hello-World"Hello-World@noreply.github.com; 
抄送: "小碟子"412054619@qq.com; 
主题: Re: [Hello-World] holy (#160)

Hi, 

 I have some basic experience on C++ and Python, I'm eager to learn more 
 things from u. Nice to hear u. 

 Chen 

 2014-08-07 10:56 GMT+02:00 baizhendie notifications@github.com:

**Comment by ciurtin** [comment]
hi
i just made an organization here on GitHub for all like us(people that wants to get start with something)so if u want to join just let me know NoobsAndPros

**Comment by kisslaay** [comment]
Yo

**Comment by sishen123258** [comment]
Join

**Comment by ciurtin** [comment]
hiMate i don't speak Chinese..so if u want to join us...we need at least to understand each other...so i would like to hear from u...but i have to understand as well
cheers

```
 On Friday, December 19, 2014 4:58 PM, sishen123258 <notifications@github.com> wrote:
```

 Join

**Comment by ciurtin** [comment]
me again...what is about 20 December 2014 in the morning...u see that is the problem if u don't try in English we will not be able to understand

```
 On Friday, December 19, 2014 5:58 PM, ady ciurtin <black_adder40@yahoo.com> wrote:
```

 hiMate i don't speak Chinese..so if u want to join us...we need at least to understand each other...so i would like to hear from u...but i have to understand as well
cheers

```
 On Friday, December 19, 2014 4:58 PM, sishen123258 <notifications@github.com> wrote:
```

 Join

**Comment by rmasciar** [comment]
Hi,
What would you like to start? Just github or do you have something else in
mind?
Roberto
Il 19/dic/2014 17:47 "ciurtin" notifications@github.com ha scritto:

**Comment by ciurtin** [comment]
hii want to start to develop some apps...but for starter i would like to see how strong the team will be...for start i want from all the people that want to jump in...to send my the best thing that they have working(even is is a simple add in C/C++....up to actual apps)Like this i will have an idea about how strong we are.
cheers

```
 On Friday, December 19, 2014 6:06 PM, rmasciar <notifications@github.com> wrote:
```

 Hi,
What would you like to start? Just github or do you have something else in
mind?
Roberto
Il 19/dic/2014 17:47 "ciurtin" notifications@github.com ha scritto:

**Comment by rmasciar** [comment]
My strongest knowledge is in R, I have some knoledge in java and python as
well as matlab but never worked on apps..
Il 19/dic/2014 19:15 "ciurtin" notifications@github.com ha scritto:

**Comment by antdp425** [comment]
Please stop doing this shit in here.

**Comment by ciurtin** [comment]
hiLike i keep on saying u guys u should also send me some of your work...to see where we stand and where we can go from there(for me is the same if is a simple add in c/c++...or an entire app)...but at least like this everybody knows where they stand...and in the same us as a team.

cheers

```
 On Friday, December 19, 2014 6:20 PM, rmasciar <notifications@github.com> wrote:
```

 My strongest knowledge is in R, I have some knoledge in java and python as
well as matlab but never worked on apps..
Il 19/dic/2014 19:15 "ciurtin" notifications@github.com ha scritto:

**Comment by allenxa** [comment]
Any one who can help me with college ACM problems please contact me: allenx@live.fr (both email and skype). Thank you so much!. I would love to improve my C++ skills under some adorable guys' guidance! I'm Allen from China, BTW.

**Comment by ashwani-pandey** [comment]
yes!1

**Comment by lonewolf9277** [comment]
I would like to contribute to some project too. I know web development
languages, C,C++, python, sql, java.

**Comment by ciurtin** [comment]
ok than here we are for all of u interested in starting some projects together...i have only one request...each one of u have to post here the best program that they can do(or if not send it to my email: black_adder40@yahoo.com)...the program have to include the source code and specification so like this we can see if we have something in common or not...a good example of such a code is Tic-Tac-Toe game...i just wait for all of you to jump in
